
language: python


python:
    - 2.7
    - 3.5
    - 3.6
    - nightly


os:
    - linux


before_install: pip install --upgrade pip setuptools wheel tox importd virtualenv --quiet


install: true


before_script: rm --recursive --force --verbose *.py[cod]


script:
    - tox

after_script: true


after_success: true


after_failure: true


cache:
  apt: true
  pip: true
